name: Semgrep
on:
  workflow_dispatch: {}
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-22.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep:pro-develop
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: | 
          apk update
          apk add openjdk17 maven
          semgrep ci --allow-local-builds --supply-chain --verbose
